import type { Metadata } from "next";

const defaultBaseUrl = process.env.NEXT_PUBLIC_BASE_URL || 'https://cribnosh.com';

export const getSiteMetadata = (baseUrl: string = defaultBaseUrl): Metadata => ({
  metadataBase: new URL(baseUrl),
  title: {
    default: "CribNosh | The app for foodies",
    template: "%s | CribNosh"
  },
  description: "Experience authentic cultural cuisine through CribNosh - your personalized meal platform connecting families with local chefs sharing traditional recipes and cultural food experiences, starting with Edinburgh.",
  keywords: [
    "Edinburgh food delivery",
    "authentic food Edinburgh",
    "local chefs Edinburgh",
    "cultural food Edinburgh",
    "home cooked meals Edinburgh",
    "Edinburgh food tech startup",
    "order meals online Edinburgh",
    "chef-made meals Edinburgh",
    "cultural food",
    "family recipes",
    "home cooked meals",
    "traditional cuisine",
    "local chefs",
    "authentic food",
    "meal platform",
    "cultural dining",
    "food delivery",
    "ethnic cuisine",
    "sustainable food",
    "healthy eating",
    "food tech startup UK",
    "order meals online UK",
    "chef-made meals UK",
    "home-cooked meals delivery UK",
    "meal delivery app UK",
    "affordable meal delivery UK",
    "best food delivery platform UK",
    "UK chef food delivery service",
    "CribNosh UK",
    "CribNosh Scotland",
    "food delivery Birmingham",
    "food delivery Leicester",
    "meal delivery Nottingham",
    "chefs in Edinburgh",
    "Edinburgh meal prep services",
    "local chefs Scotland",
    "Scotland food tech app",
    "Cook on Cribnosh on CribNosh",
    "earn money cooking UK",
    "join as a chef UK",
    "freelance chef platform",
    "chef job platform UK",
    "Food Creators wanted Edinburgh",
    "UK chef marketplace",
    "cooking from home UK",
    "CribNosh for chefs UK",
    "fresh meals delivered to your door",
    "affordable gourmet meals UK",
    "local meals to order UK",
    "meals from real chefs",
    "food delivery made easy",
    "restaurant-quality food at home",
    "trusted chefs UK",
    "Nigerian meals UK",
    "Caribbean food delivery UK",
    "vegetarian meals UK delivery",
    "halal meal delivery UK",
    "gluten-free food delivery UK",
    "traditional UK meals to order",
    "authentic homemade meals UK",
    "CribNosh login UK",
    "CribNosh chefs UK",
    "CribNosh food app",
    "chef food delivery platform",
    "order food from chefs app",
    "online chef meals UK",
    "CribNosh reviews",
    "CribNosh menu",
    "Edinburgh food entrepreneurs",
    "food delivery business UK",
    "food marketplace platform UK",
    "chef food tech platform",
    "CribNosh business model",
    "chef-powered food delivery",
    "local food tech startup",
    "food innovation Edinburgh",
    "best food delivery service in Edinburgh",
    "food delivery with Food Creators",
    "food ordering apps UK 2025",
    "local chef food options Edinburgh",
    "top chef meal platforms UK",
    "where to find Food Creators UK",
    "Edinburgh chef meal plans",
    "how to cook and sell meals legally UK",
    "best app to sell food UK",
    "food that feels like home",
    "meals with a personal touch UK",
    "experience chef cooking at home",
    "support local chefs",
    "taste of home Edinburgh",
    "meals you can trust UK",
    "real food from real chefs",
    "discover new chefs UK",
    "made-to-order food UK",
    "meal delivery Edinburgh UK",
    "chef meals UK",
    "family meals delivery UK",
    "order food online UK",
    "food delivery for busy professionals UK",
    "Edinburgh food delivery app",
    "food from local chefs",
    "ready-to-eat meals UK",
    "CribNosh order now"
  ],
  authors: [{ name: "CribNosh" }],
  creator: "CribNosh",
  publisher: "CribNosh",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    type: "website",
    siteName: "CribNosh",
    title: "CribNosh | The app for foodies",
    description: "Experience authentic cultural cuisine through CribNosh - your personalized meal platform connecting families with local chefs sharing traditional recipes and cultural food experiences.",
    images: [
      {
        url: `${baseUrl}/og-image.jpg`,
        width: 1200,
        height: 630,
        alt: "CribNosh - The app for foodies"
      }
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "CribNosh | The app for foodies",
    description: "Experience authentic cultural cuisine through CribNosh - your personalized meal platform connecting families with local chefs sharing traditional recipes and cultural food experiences.",
    images: [`${baseUrl}/twitter-image.jpg`],
    creator: "@cribnosh",
  },
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 5,
  },
  verification: {
    google: "google-site-verification-code", // Add your Google verification code
  },
  alternates: {
    canonical: baseUrl,
    languages: {
      'en-GB': 'https://cribnosh.co.uk',
      'en-US': 'https://cribnosh.com',
      'x-default': 'https://cribnosh.com',
    },
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
});

export const metadata: Metadata = getSiteMetadata();