import type { Metadata } from "next";

const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || 'https://cribnosh.com';

export const metadata: Metadata = {
  metadataBase: new URL(baseUrl),
  title: {
    default: "CribNosh | The app for foodies",
    template: "%s | CribNosh"
  },
  description: "Experience authentic cultural cuisine through CribNosh - your personalized meal platform connecting families with local chefs sharing traditional recipes and cultural food experiences.",
  keywords: [
    "cultural food",
    "family recipes",
    "home cooked meals",
    "traditional cuisine",
    "local chefs",
    "authentic food",
    "meal platform",
    "cultural dining",
    "food delivery",
    "ethnic cuisine",
    "sustainable food",
    "healthy eating",
    "food tech startup UK",
    "order meals online UK",
    "chef-made meals UK",
    "home-cooked meals delivery UK",
    "meal delivery app UK",
    "food delivery Midlands",
    "affordable meal delivery UK",
    "best food delivery platform UK",
    "UK chef food delivery service",
    "CribNosh UK",
    "food delivery Birmingham",
    "food delivery Leicester",
    "meal delivery Nottingham",
    "chefs in the Midlands UK",
    "Birmingham meal prep services",
    "Leicester home-cooked meals",
    "Nottingham food delivery app",
    "Midlands food startup",
    "local chefs Midlands",
    "Midlands food tech app",
    "Cook on Cribnosh on CribNosh",
    "earn money cooking UK",
    "join as a chef UK",
    "freelance chef platform",
    "chef job platform UK",
    "Food Creators wanted Midlands",
    "UK chef marketplace",
    "cooking from home UK",
    "CribNosh for chefs UK",
    "fresh meals delivered to your door",
    "chef-curated meals Midlands",
    "affordable gourmet meals UK",
    "healthy food delivery Midlands",
    "local meals to order UK",
    "meals from real chefs",
    "food delivery made easy",
    "restaurant-quality food at home",
    "trusted chefs UK",
    "Nigerian meals UK",
    "Caribbean food delivery Midlands",
    "vegetarian meals UK delivery",
    "halal meal delivery UK",
    "gluten-free food delivery UK",
    "traditional UK meals to order",
    "comfort food delivery Midlands",
    "Sunday roast delivery UK",
    "authentic homemade meals UK",
    "CribNosh login UK",
    "CribNosh chefs UK",
    "CribNosh Midlands",
    "CribNosh food app",
    "chef food delivery platform",
    "order food from chefs app",
    "online chef meals UK",
    "CribNosh reviews",
    "CribNosh menu",
    "Midlands food entrepreneurs",
    "food delivery business UK",
    "food marketplace platform UK",
    "chef food tech platform",
    "CribNosh business model",
    "cloud kitchen Midlands",
    "chef-powered food delivery",
    "local food tech startup",
    "food innovation Midlands",
    "best food delivery service in the Midlands",
    "food delivery with Food Creators",
    "food ordering apps UK 2025",
    "local chef food options Midlands",
    "top chef meal platforms UK",
    "where to find Food Creators UK",
    "Midlands chef meal plans",
    "how to cook and sell meals legally UK",
    "best app to sell food UK",
    "food that feels like home",
    "meals with a personal touch UK",
    "experience chef cooking at home",
    "support local chefs",
    "taste of home Midlands",
    "meals you can trust UK",
    "real food from real chefs",
    "discover new chefs UK",
    "made-to-order food UK",
    "meal delivery Midlands UK",
    "chef meals UK",
    "family meals delivery UK",
    "order food online Midlands",
    "food delivery for busy professionals UK",
    "Midlands food delivery app",
    "food from local chefs",
    "ready-to-eat meals UK",
    "CribNosh order now"
  ],
  authors: [{ name: "CribNosh" }],
  creator: "CribNosh",
  publisher: "CribNosh",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    type: "website",
    siteName: "CribNosh",
    title: "CribNosh | The app for foodies",
    description: "Experience authentic cultural cuisine through CribNosh - your personalized meal platform connecting families with local chefs sharing traditional recipes and cultural food experiences.",
    images: [
      {
        url: `${baseUrl}/og-image.jpg`,
        width: 1200,
        height: 630,
        alt: "CribNosh - The app for foodies"
      }
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "CribNosh | The app for foodies",
    description: "Experience authentic cultural cuisine through CribNosh - your personalized meal platform connecting families with local chefs sharing traditional recipes and cultural food experiences.",
    images: [`${baseUrl}/twitter-image.jpg`],
    creator: "@cribnosh",
  },
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 5,
  },
  verification: {
    google: "google-site-verification-code", // Add your Google verification code
  },
  alternates: {
    canonical: baseUrl,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
}; 